[fleet]
dell-7050 ansible_host=100.117.229.28
sony      ansible_host=100.96.120.65
hp-nas    ansible_host=100.64.249.4
lenovo    ansible_host=100.66.222.35
dell-5070 ansible_host=100.108.102.105
dell-7440 ansible_host=100.106.110.55
pi        ansible_host=100.73.143.19

[fleet:vars]
ansible_user=michael
ansible_ssh_common_args='-o ConnectTimeout=5 -o BatchMode=yes'

[dad_tailnet]
vt-pc ansible_host=100.102.26.15 ansible_user=chris

[dad_tailnet:vars]
ansible_ssh_common_args='-o ConnectTimeout=5 -o BatchMode=yes'
